name: Test

on:
  push:
    branches: 
      - initial-branch
  pull_request:
    branches: 
      - initial-branch

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Install go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - uses: actions/checkout@v2

    - name: Install logrus
      run: |
       go version
       go get -u github.com/sirupsen/logrus

    - name: Install clientv3
      run: |
       go version
       go get -u go.etcd.io/etcd/clientv3

    - name: Test
      run: go test ./...